import exported from "@subrosa/chat-core/agent-lite.json";

/**
 * What the web client knows of agent-lite and of the sync codec, generated by
 * Rust (`src-tauri/src/agent_lite/web_client_export.rs`) so neither the
 * prompt prose nor the table allowlist is written a second time here.
 */
export interface AgentLiteExport {
  systemPrompt: string;
  defaultModel: string;
  finalAnswerNudge: string;
  memoryBlockHeader: string;
  injectedMemoryLimit: number;
  personalization: {
    header: string;
    about: string;
    style: string;
    personality: string;
    maxFieldChars: number;
    personalities: Record<string, string>;
  };
  limits: { maxToolRounds: number; webSearchResults: number; webPageChars: number };
  tools: ToolDefinition[];
  tables: Record<TableName, { kind: SyncKind; columns: string[] }>;
  /** `data_cards::CARDS_PROMPT`: how to write chart and table blocks. */
  cardsPrompt: string;
  /** The project section, piece by piece, and its file search (ADR-0085). */
  project: {
    opening: string;
    instructions: string;
    files: string;
    ownMemory: string;
    memoryDefault: string;
    memoryProject: string;
    tool: ToolDefinition;
  };
  /** Past chats (ADR-0081): the block's words, its limits and the tool. */
  pastChats: {
    header: string;
    excerptsIntro: string;
    userLine: string;
    assistantLine: string;
    turnSnippets: number;
    blockChars: number;
    snippetChars: number;
    titleChars: number;
    toolResults: number;
    tool: ToolDefinition;
  };
  /** A custom assistant's prompt and reference search (ADR-0058). */
  assistant: { systemPrompt: string; searchReferences: ToolDefinition };
  /** The canvas rewrite (ADR-0087) and the picture refine pass (ADR-0088). */
  editing: {
    canvas: {
      system: string;
      message: string;
      temperature: number;
      maxChars: number;
      promptVersion: string;
    };
    refine: { critiqueSystem: string; editSuffix: string; maxPasses: number; editModels: string[] };
  };
}
export interface ToolDefinition {
  type: "function";
  function: { name: string; description: string; parameters: Record<string, unknown> };
}

export const AGENT_LITE = exported as unknown as AgentLiteExport;

/** The routing classes a browser device reads and writes. Bounded on purpose:
 * the page holds a decryption key, so what it may pull is a decision. Within a
 * kind, only the tables below are decrypted into the page; any other table of
 * that kind (a health day, a recording) is left unread and uncached. */
export const WEB_KINDS = [
  "conversation",
  "memory",
  "note",
  "folder",
  "artifact",
  "settings",
] as const;
export type SyncKind = (typeof WEB_KINDS)[number];

export type TableName =
  | "agent_tasks"
  | "agent_messages"
  | "memories"
  | "notes"
  | "folders"
  | "account_session_folders"
  | "project_settings"
  | "project_files"
  | "saved_items"
  | "assistants"
  | "assistant_references"
  | "account_studio_files"
  | "account_file_manifests";

export type Cell = string | number | null;
export type Row = Record<string, Cell>;

/** The authenticated body table of a custom assistant's conversation. It is
 * read like `agent_tasks`, and written from a browser only as a custom
 * assistant's own conversation, its snapshot riding beside the row. */
export const ASSISTANT_CONVERSATIONS = "assistant_conversations";

/** Whether a received body names a table this page reads. */
export function knownTable(name: unknown): boolean {
  return (
    typeof name === "string" &&
    (name === ASSISTANT_CONVERSATIONS || Object.hasOwn(AGENT_LITE.tables, name))
  );
}

export function tableOf(name: string): { name: TableName; kind: SyncKind; columns: string[] } {
  const resolved = name === ASSISTANT_CONVERSATIONS ? "agent_tasks" : name;
  const table = AGENT_LITE.tables[resolved as TableName];
  if (!table) throw new Error("Unknown synchronised table");
  return { name: resolved as TableName, ...table };
}

/** A row as it travels: every allowlisted column, nothing else. A column the
 * caller did not name travels as null, the way SQLite would have stored it. */
export function travellingRow(name: TableName, values: Row): Row {
  const { columns } = tableOf(name);
  const row: Row = {};
  for (const column of columns) {
    const value = values[column];
    if (value !== undefined) row[column] = value;
    else if (!(name === "memories" && column === "scope")) row[column] = null;
  }
  return row;
}

/** Whether a received row only names columns the codec allows, with values a
 * column can hold. The same check `account/sync.rs` makes before applying. */
export function validRow(name: string, row: unknown): row is Row {
  if (!row || typeof row !== "object" || Array.isArray(row)) return false;
  let columns: string[];
  try {
    columns = tableOf(name).columns;
  } catch {
    return false;
  }
  return Object.entries(row as Record<string, unknown>).every(
    ([key, value]) =>
      columns.includes(key) &&
      (value === null || typeof value === "string" || typeof value === "number"),
  );
}

/** Timestamps as the app writes them: RFC 3339 with milliseconds, in UTC. */
export function timestamp(now = new Date()): string {
  return now.toISOString();
}
