/**
 * A browser admitted as a device of its account (ADR 0096).
 *
 * Two keys live here, both generated by WebCrypto as non-extractable
 * CryptoKeys and kept in IndexedDB, never in localStorage:
 *
 * - the device key (ECDSA P-256), which signs every request that acts as the
 *   device. The service holds its public half. A script on this page can ask
 *   it to sign while the page is open; no script can copy it out.
 * - a wrapping key (AES-GCM), which seals the `cdm_` key Carpe Diem minted for
 *   this browser, so what sits on disk is ciphertext bound to this account and
 *   this device.
 *
 * Key birth follows ADR 0069 with a browser bound: a fresh ephemeral P-256 key
 * per attempt, held in memory only; a 120 second assertion from the account
 * service; a DPoP proof to Carpe Diem, which mints the key and returns it here
 * over TLS. The key is short lived and renewed while the device is live.
 */
import { ApiError, api, boundedJson } from "./api";
import { accountOrigin } from "./office-origins";
import { decode, encode } from "./vault";

/** Where key birth and inference happen. The site's CSP `connect-src` names
 * this origin and nothing else beyond its own. */
export const CARPE_DIEM_OPERATOR = operatorRoot(import.meta.env.VITE_CARPE_DIEM_OPERATOR);
/** Production unless a development build names a local operator. */
export function operatorRoot(configured: string | undefined): string {
  if (
    configured &&
    /^(https:\/\/[^/]+|http:\/\/(127\.0\.0\.1|localhost)(:\d+)?)(\/[\w/-]*)?$/.test(configured)
  )
    return configured.replace(/\/+$/, "");
  return "https://carpe-diem.xyz/api/operator";
}
export const DEVICE_PROOF_TYPE = "subrosa-device+jwt";
export const DEVICE_PROOF_HEADER = "subrosa-device-proof";
/** Renew when less than this is left, so a person who opens the site every few
 * days never meets an expired key, and renewals stay well under Carpe Diem's
 * three issuances a day per account. */
export const RENEW_BEFORE_MS = 2 * 24 * 3600_000;

const encoder = new TextEncoder();
const decoder = new TextDecoder("utf-8", { fatal: true });

export interface StoredKey {
  iv: string;
  ciphertext: string;
  keyId: string;
  prefix: string;
  expiresAt: string;
  dailyCapCredits: number | null;
}
export interface DeviceRecord {
  accountId: string;
  /** Null between generating the key and the service admitting it. */
  deviceId: string | null;
  name: string;
  x: string;
  y: string;
  signing: CryptoKey;
  wrapping: CryptoKey;
  key: StoredKey | null;
}
/** Where records live. IndexedDB in the page; an in-memory map in tests. */
export interface DeviceStore {
  get(accountId: string): Promise<DeviceRecord | null>;
  put(record: DeviceRecord): Promise<void>;
  delete(accountId: string): Promise<void>;
}

// ── IndexedDB ───────────────────────────────────────────────────────────────

const DB_NAME = "subrosa-browser-device";
const STORE = "devices";

function openDb(): Promise<IDBDatabase> {
  return new Promise((resolve, reject) => {
    const request = indexedDB.open(DB_NAME, 1);
    request.onupgradeneeded = () => {
      if (!request.result.objectStoreNames.contains(STORE))
        request.result.createObjectStore(STORE, { keyPath: "accountId" });
    };
    request.onsuccess = () => resolve(request.result);
    request.onerror = () => reject(request.error);
  });
}
async function inStore<T>(
  mode: IDBTransactionMode,
  action: (store: IDBObjectStore) => IDBRequest,
): Promise<T> {
  const db = await openDb();
  try {
    return await new Promise<T>((resolve, reject) => {
      const tx = db.transaction(STORE, mode);
      const request = action(tx.objectStore(STORE));
      tx.oncomplete = () => resolve(request.result as T);
      tx.onerror = () => reject(tx.error);
      tx.onabort = () => reject(tx.error);
    });
  } finally {
    db.close();
  }
}
export const indexedDbStore: DeviceStore = {
  async get(accountId) {
    return (await inStore<DeviceRecord | undefined>("readonly", (s) => s.get(accountId))) ?? null;
  },
  async put(record) {
    await inStore("readwrite", (s) => s.put(record));
  },
  async delete(accountId) {
    await inStore("readwrite", (s) => s.delete(accountId));
  },
};

// ── JOSE, by hand, like the service and Carpe Diem check it ────────────────

const json64 = (value: unknown) => encode(encoder.encode(JSON.stringify(value)));
async function sha256(value: string): Promise<string> {
  return encode(new Uint8Array(await crypto.subtle.digest("SHA-256", encoder.encode(value))));
}
/** RFC 7638 thumbprint of a P-256 public key. */
export function thumbprint(x: string, y: string): Promise<string> {
  return sha256(`{"crv":"P-256","kty":"EC","x":"${x}","y":"${y}"}`);
}
/** WebCrypto's ECDSA output is already the raw `r||s` a JWS wants. */
async function signJws(key: CryptoKey, header: object, claims: object): Promise<string> {
  const input = `${json64(header)}.${json64(claims)}`;
  const signature = await crypto.subtle.sign(
    { name: "ECDSA", hash: "SHA-256" },
    key,
    encoder.encode(input),
  );
  return `${input}.${encode(new Uint8Array(signature))}`;
}
async function proofClaims(htu: string, bound?: string) {
  return {
    htm: "POST",
    htu,
    iat: Math.floor(Date.now() / 1000),
    jti: crypto.randomUUID(),
    ...(bound === undefined ? {} : { ath: await sha256(bound) }),
  };
}
async function newSigningPair() {
  const pair = (await crypto.subtle.generateKey({ name: "ECDSA", namedCurve: "P-256" }, false, [
    "sign",
    "verify",
  ])) as CryptoKeyPair;
  const jwk = await crypto.subtle.exportKey("jwk", pair.publicKey);
  if (typeof jwk.x !== "string" || typeof jwk.y !== "string") throw new Error("Invalid key");
  return { privateKey: pair.privateKey, x: jwk.x, y: jwk.y };
}

/**
 * A proof that this browser acts as its device, for one call to `path` on the
 * account service with exactly `body`: `ath` is the SHA-256 of the body as
 * sent, so the service refuses the proof on any other body. Build the body
 * string once and send that same string. An Office pane runs on an origin of
 * its own, so the URL it signs is the account origin's, which the service
 * checks, not the page's.
 */
export async function deviceProof(
  record: DeviceRecord,
  path: string,
  body: string,
  origin = accountOrigin(),
): Promise<string> {
  const header = record.deviceId
    ? { alg: "ES256", typ: DEVICE_PROOF_TYPE, kid: record.deviceId }
    : {
        alg: "ES256",
        typ: DEVICE_PROOF_TYPE,
        jwk: { kty: "EC", crv: "P-256", x: record.x, y: record.y },
      };
  return signJws(record.signing, header, await proofClaims(`${origin}${path}`, body));
}

// ── Naming ──────────────────────────────────────────────────────────────────

/** The family a person recognises, never the version or the platform. */
export function browserFamily(userAgent: string): string {
  if (/Edg\//.test(userAgent)) return "Edge";
  if (/OPR\/|Opera/.test(userAgent)) return "Opera";
  if (/Firefox\/|FxiOS\//.test(userAgent)) return "Firefox";
  if (/Chrome\/|CriOS\//.test(userAgent)) return "Chrome";
  if (/Safari\//.test(userAgent)) return "Safari";
  return "";
}

// ── Admission ───────────────────────────────────────────────────────────────

export type Admission = { pairing_request_id: string } | { recovery_proof: string };

/**
 * Makes this browser a device. The key pair is written before the request,
 * so a lost answer leaves a record to clean up rather than a device the
 * browser cannot sign for; a refusal removes it.
 */
export async function admitBrowser(
  store: DeviceStore,
  accountId: string,
  name: string,
  admission: Admission,
): Promise<DeviceRecord> {
  const signing = await newSigningPair();
  const wrapping = await crypto.subtle.generateKey({ name: "AES-GCM", length: 256 }, false, [
    "encrypt",
    "decrypt",
  ]);
  const record: DeviceRecord = {
    accountId,
    deviceId: null,
    name,
    x: signing.x,
    y: signing.y,
    signing: signing.privateKey,
    wrapping,
    key: null,
  };
  await store.put(record);
  try {
    const body = JSON.stringify({ name, admission });
    const device = await api<{ id: string; name: string }>("/api/v1/browser-devices", {
      method: "POST",
      headers: {
        [DEVICE_PROOF_HEADER]: await deviceProof(record, "/api/v1/browser-devices", body),
      },
      body,
    });
    const admitted = { ...record, deviceId: device.id, name: device.name };
    await store.put(admitted);
    return admitted;
  } catch (error) {
    await store.delete(accountId).catch(() => undefined);
    throw error;
  }
}

// ── The minted key, sealed at rest ─────────────────────────────────────────

const keyContext = (record: DeviceRecord) =>
  encoder.encode(`subrosa:browser-key:v1:${record.accountId}:${record.deviceId}`);

export async function sealKey(
  record: DeviceRecord,
  issued: {
    key: string;
    keyId: string;
    prefix: string;
    expiresAt: string;
    dailyCapCredits: number | null;
  },
): Promise<StoredKey> {
  const iv = crypto.getRandomValues(new Uint8Array(12));
  const plaintext = encoder.encode(issued.key);
  try {
    const ciphertext = await crypto.subtle.encrypt(
      { name: "AES-GCM", iv, additionalData: keyContext(record), tagLength: 128 },
      record.wrapping,
      plaintext,
    );
    return {
      iv: encode(iv),
      ciphertext: encode(new Uint8Array(ciphertext)),
      keyId: issued.keyId,
      prefix: issued.prefix,
      expiresAt: issued.expiresAt,
      dailyCapCredits: issued.dailyCapCredits,
    };
  } finally {
    plaintext.fill(0);
  }
}
/** The `cdm_` key, opened for one use. Null when there is none or it expired. */
export async function openKey(record: DeviceRecord, now = Date.now()): Promise<string | null> {
  const stored = record.key;
  if (!stored || Date.parse(stored.expiresAt) <= now) return null;
  const plaintext = await crypto.subtle.decrypt(
    { name: "AES-GCM", iv: decode(stored.iv), additionalData: keyContext(record), tagLength: 128 },
    record.wrapping,
    decode(stored.ciphertext),
  );
  return decoder.decode(plaintext);
}
export function needsRenewal(record: DeviceRecord | null, now = Date.now()): boolean {
  if (!record?.deviceId) return false;
  if (!record.key) return true;
  return Date.parse(record.key.expiresAt) - now < RENEW_BEFORE_MS;
}

// ── Key birth ───────────────────────────────────────────────────────────────

export type Birth =
  | { status: "issued"; record: DeviceRecord }
  | {
      status: "confirmation_required";
      code: string;
      emailHint: string;
      expiresAt: string;
      /** Polls Carpe Diem with the same ephemeral key; call until it is done. */
      poll: () => Promise<Birth | { status: "pending" }>;
    };

interface Issued {
  status: "issued";
  key: string;
  keyId: string;
  prefix: string;
  expiresAt?: string;
  bound?: { kind?: string; dailyCapCredits?: number };
}

async function operator(
  path: string,
  init: { headers: Record<string, string>; body: string },
): Promise<{ status: number; body: Record<string, unknown> }> {
  const response = await fetch(`${CARPE_DIEM_OPERATOR}${path}`, {
    method: "POST",
    headers: { ...init.headers, "Content-Type": "application/json", Accept: "application/json" },
    body: init.body,
    credentials: "omit",
    redirect: "error",
    referrerPolicy: "no-referrer",
    signal: AbortSignal.timeout(20000),
  });
  const body = (await boundedJson(response)) as Record<string, unknown> | null;
  return { status: response.status, body: body ?? {} };
}

async function keep(
  store: DeviceStore,
  record: DeviceRecord,
  issued: Issued,
): Promise<DeviceRecord> {
  if (typeof issued.key !== "string" || !issued.key.startsWith("cdm_"))
    throw new ApiError("invalid_response", "Carpe Diem returned no key.", 502);
  // An operator that does not hold the browser bound yet would hand over an
  // unbounded key. A browser never keeps one: it revokes it on the spot.
  const expiresAt = issued.expiresAt;
  if (
    issued.bound?.kind !== "browser" ||
    typeof issued.bound.dailyCapCredits !== "number" ||
    typeof expiresAt !== "string" ||
    Number.isNaN(Date.parse(expiresAt))
  ) {
    await operator("/v1/keys/self/revoke", {
      headers: { Authorization: `Bearer ${issued.key}` },
      body: "{}",
    }).catch(() => undefined);
    throw new ApiError("unbounded_key", "Carpe Diem returned a key without its bound.", 502);
  }
  const key = await sealKey(record, {
    key: issued.key,
    keyId: issued.keyId,
    prefix: issued.prefix,
    expiresAt,
    dailyCapCredits: issued.bound.dailyCapCredits,
  });
  const next = { ...record, key };
  await store.put(next);
  return next;
}

function carpeDiemError(status: number, body: Record<string, unknown>): ApiError {
  return new ApiError(
    typeof body.code === "string" ? body.code : "carpe_diem_unavailable",
    "Carpe Diem could not issue a key.",
    status,
  );
}

/**
 * Asks the service for an assertion as this browser device, then Carpe Diem
 * for the key. The ephemeral key exists only inside this call and the poll it
 * may hand back.
 */
export async function birthKey(store: DeviceStore, record: DeviceRecord): Promise<Birth> {
  if (!record.deviceId) throw new ApiError("device_required", "This browser is not a device.", 403);
  const ephemeral = await newSigningPair();
  const jwk = { kty: "EC", crv: "P-256", x: ephemeral.x, y: ephemeral.y };
  const jkt = await thumbprint(ephemeral.x, ephemeral.y);
  const request = JSON.stringify({ jkt });
  const { assertion } = await api<{ assertion: string }>("/api/v1/carpe-diem/assertion", {
    method: "POST",
    headers: {
      [DEVICE_PROOF_HEADER]: await deviceProof(record, "/api/v1/carpe-diem/assertion", request),
    },
    body: request,
  });
  const dpop = async (path: string, bound: string) =>
    signJws(
      ephemeral.privateKey,
      { alg: "ES256", typ: "dpop+jwt", jwk },
      await proofClaims(`${CARPE_DIEM_OPERATOR}${path}`, bound),
    );
  const { status, body } = await operator("/partner/keys", {
    headers: {
      Authorization: `PartnerAssertion ${assertion}`,
      DPoP: await dpop("/partner/keys", assertion),
    },
    body: "{}",
  });
  if (status === 201)
    return { status: "issued", record: await keep(store, record, body as unknown as Issued) };
  if (status === 202 && typeof body.linkRequestId === "string") {
    const linkRequestId = body.linkRequestId;
    const poll = async (): Promise<Birth | { status: "pending" }> => {
      const answer = await operator("/partner/keys/poll", {
        headers: { DPoP: await dpop("/partner/keys/poll", linkRequestId) },
        body: JSON.stringify({ linkRequestId }),
      });
      if (answer.status === 202) return { status: "pending" };
      if (answer.status === 201)
        return {
          status: "issued",
          record: await keep(store, record, answer.body as unknown as Issued),
        };
      throw carpeDiemError(answer.status, answer.body);
    };
    return {
      status: "confirmation_required",
      code: String(body.code ?? ""),
      emailHint: String(body.emailHint ?? ""),
      expiresAt: String(body.expiresAt ?? ""),
      poll,
    };
  }
  throw carpeDiemError(status, body);
}

// ── Leaving ─────────────────────────────────────────────────────────────────

/**
 * Stops being a device: the service revokes it (and queues the Carpe Diem
 * revocation), the key revokes itself at Carpe Diem at once, and the local
 * keys are deleted. Each step is attempted even when an earlier one failed,
 * because a browser that cannot reach the service must still forget.
 */
export async function forgetBrowser(store: DeviceStore, record: DeviceRecord): Promise<void> {
  const attempts: Promise<unknown>[] = [];
  if (record.deviceId)
    attempts.push(
      deviceProof(record, "/api/v1/browser-devices/renounce", "{}").then((proof) =>
        api("/api/v1/browser-devices/renounce", {
          method: "POST",
          headers: { [DEVICE_PROOF_HEADER]: proof },
          body: "{}",
        }),
      ),
    );
  attempts.push(
    openKey(record, 0).then((key) =>
      key
        ? operator("/v1/keys/self/revoke", {
            headers: { Authorization: `Bearer ${key}` },
            body: "{}",
          })
        : null,
    ),
  );
  await Promise.allSettled(attempts);
  await store.delete(record.accountId);
}
