// The three add-in manifests (ADR-0102), one per host, written from one
// template so their URLs, icons and wording cannot drift apart.
//
//   node office-addins/scripts/manifests.mjs            # rewrite manifests/
//   node office-addins/scripts/manifests.mjs --check    # fail if they are stale
//   node office-addins/scripts/manifests.mjs --origin https://localhost:1431 \
//     --account-origin https://localhost:1430 --out /tmp/dev
//
// The panes run on the add-ins' own origin (ADR-0102, addendum of
// 2026-10-10), never the account's: `--origin` is that office origin, and
// `--account-origin` the account's, which the manifest lists in AppDomains so
// the sign-in window may go there to sign in. The committed manifests name the
// production origins; a development or staging pair gets its own copies with
// --origin, --account-origin and --out.

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  PRODUCTION_ACCOUNT_ORIGIN,
  PRODUCTION_OFFICE_ORIGIN,
} from "../../scripts/office-origins.mjs";

/** Where the panes are served: the office origin. */
export const PRODUCTION_ORIGIN = PRODUCTION_OFFICE_ORIGIN;
export const ACCOUNT_ORIGIN = PRODUCTION_ACCOUNT_ORIGIN;

/** One entry per host. The ids are fixed: Office keys a sideloaded add-in by
 * them, and a new id is a different add-in. */
export const HOSTS = [
  {
    file: "word.xml",
    page: "word",
    id: "e6483947-692c-4283-8ebc-561d9c1ed41c",
    host: "Document",
    name: "Word",
    requirement: ["WordApi", "1.1"],
  },
  {
    file: "excel.xml",
    page: "excel",
    id: "b773a250-08d1-4050-a2a7-e7f5e29c07e6",
    host: "Workbook",
    name: "Excel",
    requirement: ["ExcelApi", "1.4"],
  },
  {
    file: "powerpoint.xml",
    page: "powerpoint",
    id: "b45c0923-07d3-47aa-810e-9999eef01f54",
    host: "Presentation",
    name: "PowerPoint",
    requirement: ["PowerPointApi", "1.1"],
  },
];

/** 1.0.1.0: the panes moved to their own origin. Same ids, so Office takes
 * the new manifest as an update of the same add-in. */
export const VERSION = "1.0.1.0";

const xmlEscape = (value) =>
  value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

const WORDS = {
  description: {
    "en-US": (name) =>
      `${WHAT[name]["en-US"]} with Sub Rosa. Every change is shown to you before it is made.`,
    "fr-FR": (name) =>
      `${WHAT[name]["fr-FR"]} avec Sub Rosa. Chaque modification vous est montrée avant d’être faite.`,
  },
  group: { "en-US": "Sub Rosa", "fr-FR": "Sub Rosa" },
  open: { "en-US": "Open Sub Rosa", "fr-FR": "Ouvrir Sub Rosa" },
  tip: {
    "en-US": "Ask Sub Rosa about this document, and review every change before it is made.",
    "fr-FR":
      "Interrogez Sub Rosa sur ce document, et relisez chaque modification avant qu’elle soit faite.",
  },
};
const WHAT = {
  Word: {
    "en-US": "Rewrite, summarize and translate the selection, or draft at the cursor,",
    "fr-FR": "Reformulez, résumez et traduisez la sélection, ou rédigez au curseur,",
  },
  Excel: {
    "en-US": "Explain and write formulas, and analyse a range,",
    "fr-FR": "Expliquez et écrivez des formules, et analysez une plage,",
  },
  PowerPoint: {
    "en-US": "Draft slides from a request or a note",
    "fr-FR": "Rédigez des diapositives à partir d’une demande ou d’une note",
  },
};

const httpsOrigin = (origin) => {
  const url = new URL(origin);
  if (url.protocol !== "https:" || url.origin !== origin)
    throw new Error("The origin must be an HTTPS origin without a path.");
  return origin;
};

/** The manifest of one host, for the panes' origin `origin` and the account
 * origin `account`. */
export function manifest(entry, origin = PRODUCTION_ORIGIN, account = ACCOUNT_ORIGIN) {
  httpsOrigin(origin);
  httpsOrigin(account);
  if (origin === account) throw new Error("The panes need an origin apart from the account's.");
  const pane = `${origin}/office/${entry.page}.html`;
  const icon = (size) => `${origin}/office/icon-${size}.png`;
  const override = (text, prefix = "") =>
    `<${prefix}Override Locale="fr-FR" Value="${xmlEscape(text)}"/>`;
  const description = WORDS.description["en-US"](entry.name);
  const [set, version] = entry.requirement;
  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by office-addins/scripts/manifests.mjs (ADR-0102). Edit the script, not this file. -->
<OfficeApp xmlns="http://schemas.microsoft.com/office/appforoffice/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bt="http://schemas.microsoft.com/office/officeappbasictypes/1.0" xmlns:ov="http://schemas.microsoft.com/office/taskpaneappversionoverrides" xsi:type="TaskPaneApp">
  <Id>${entry.id}</Id>
  <Version>${VERSION}</Version>
  <ProviderName>Sub Rosa</ProviderName>
  <DefaultLocale>en-US</DefaultLocale>
  <DisplayName DefaultValue="Sub Rosa for ${entry.name}">
    <Override Locale="fr-FR" Value="Sub Rosa pour ${entry.name}"/>
  </DisplayName>
  <Description DefaultValue="${xmlEscape(description)}">
    ${override(WORDS.description["fr-FR"](entry.name))}
  </Description>
  <IconUrl DefaultValue="${icon(32)}"/>
  <HighResolutionIconUrl DefaultValue="${icon(64)}"/>
  <SupportUrl DefaultValue="${account}/help"/>
  <AppDomains>
    <AppDomain>${account}</AppDomain>
  </AppDomains>
  <Hosts>
    <Host Name="${entry.host}"/>
  </Hosts>
  <Requirements>
    <Sets DefaultMinVersion="${version}">
      <Set Name="${set}" MinVersion="${version}"/>
    </Sets>
  </Requirements>
  <DefaultSettings>
    <SourceLocation DefaultValue="${pane}"/>
  </DefaultSettings>
  <Permissions>ReadWriteDocument</Permissions>
  <VersionOverrides xmlns="http://schemas.microsoft.com/office/taskpaneappversionoverrides" xsi:type="VersionOverridesV1_0">
    <Hosts>
      <Host xsi:type="${entry.host}">
        <DesktopFormFactor>
          <FunctionFile resid="Commands.Url"/>
          <ExtensionPoint xsi:type="PrimaryCommandSurface">
            <OfficeTab id="TabHome">
              <Group id="SubRosa.Group">
                <Label resid="SubRosa.Group.Label"/>
                <Icon>
                  <bt:Image size="16" resid="Icon.16"/>
                  <bt:Image size="32" resid="Icon.32"/>
                  <bt:Image size="80" resid="Icon.80"/>
                </Icon>
                <Control xsi:type="Button" id="SubRosa.Open">
                  <Label resid="SubRosa.Open.Label"/>
                  <Supertip>
                    <Title resid="SubRosa.Open.Label"/>
                    <Description resid="SubRosa.Open.Tip"/>
                  </Supertip>
                  <Icon>
                    <bt:Image size="16" resid="Icon.16"/>
                    <bt:Image size="32" resid="Icon.32"/>
                    <bt:Image size="80" resid="Icon.80"/>
                  </Icon>
                  <Action xsi:type="ShowTaskpane">
                    <TaskpaneId>SubRosa.Pane</TaskpaneId>
                    <SourceLocation resid="Pane.Url"/>
                  </Action>
                </Control>
              </Group>
            </OfficeTab>
          </ExtensionPoint>
        </DesktopFormFactor>
      </Host>
    </Hosts>
    <Resources>
      <bt:Images>
        <bt:Image id="Icon.16" DefaultValue="${icon(16)}"/>
        <bt:Image id="Icon.32" DefaultValue="${icon(32)}"/>
        <bt:Image id="Icon.80" DefaultValue="${icon(80)}"/>
      </bt:Images>
      <bt:Urls>
        <bt:Url id="Pane.Url" DefaultValue="${pane}"/>
        <bt:Url id="Commands.Url" DefaultValue="${origin}/office/commands.html"/>
      </bt:Urls>
      <bt:ShortStrings>
        <bt:String id="SubRosa.Group.Label" DefaultValue="${xmlEscape(WORDS.group["en-US"])}">
          ${override(WORDS.group["fr-FR"], "bt:")}
        </bt:String>
        <bt:String id="SubRosa.Open.Label" DefaultValue="${xmlEscape(WORDS.open["en-US"])}">
          ${override(WORDS.open["fr-FR"], "bt:")}
        </bt:String>
      </bt:ShortStrings>
      <bt:LongStrings>
        <bt:String id="SubRosa.Open.Tip" DefaultValue="${xmlEscape(WORDS.tip["en-US"])}">
          ${override(WORDS.tip["fr-FR"], "bt:")}
        </bt:String>
      </bt:LongStrings>
    </Resources>
  </VersionOverrides>
</OfficeApp>
`;
}

const here = dirname(fileURLToPath(import.meta.url));

function main(argv) {
  const option = (name) => {
    const at = argv.indexOf(name);
    return at >= 0 ? argv[at + 1] : undefined;
  };
  const origin = option("--origin") ?? PRODUCTION_ORIGIN;
  const account = option("--account-origin") ?? ACCOUNT_ORIGIN;
  const out = option("--out") ?? join(here, "..", "manifests");
  const check = argv.includes("--check");
  let stale = 0;
  if (!check) mkdirSync(out, { recursive: true });
  for (const entry of HOSTS) {
    const path = join(out, entry.file);
    const text = manifest(entry, origin, account);
    if (check) {
      let committed = "";
      try {
        committed = readFileSync(path, "utf8");
      } catch {
        // Missing counts as stale.
      }
      if (committed !== text) {
        process.stderr.write(`${path} is stale: run node office-addins/scripts/manifests.mjs\n`);
        stale++;
      }
    } else writeFileSync(path, text);
  }
  if (stale) process.exit(1);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url))
  main(process.argv.slice(2));
